apiVersion: apps/v1
kind: Deployment
metadata:
  name: colab-api
  namespace: jhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colab-api
  template:
    metadata:
      labels:
        app: colab-api
    spec:
      serviceAccountName: colab-backend
      containers:
      - name: api
        image: jupyter-api:dev
        env:
        - name: JUPYTER_BASE
          value: "http://proxy-public:80" # when JupyterHub exposes proxy
        - name: DEV_JUPYTER_TOKEN
          value: "devtoken"
        - name: JWT_SECRET
          value: "change-this-in-prod"
        - name: K8S_ENABLED
          value: "true"
        - name: K8S_NAMESPACE
          value: "jhub"
        - name: NOTEBOOK_IMAGE
          value: "jupyter-singleuser:dev"
        - name: NOTEBOOK_PORT
          value: "8888"
        - name: NOTEBOOK_BASE_URL_PREFIX
          value: "/jupyter"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: colab-api
  namespace: jhub
spec:
  selector:
    app: colab-api
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
